[project]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "pytorchnanigans"
name = "pytorchnanigans"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
scratchpad = "jupyter notebook notebooks/scratchpad.ipynb"

[dependencies]
max = "~=24.6"
pytorch = "==2.4.0"
numpy = ">=1.26.4,<2"
jupyter = ">=1.1.1,<2"
