[project]
authors = ["Kevin Bi <kevinbi075@gmail.com>"]
channels = ["https://conda.modular.com/max", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Add a short description here"
name = "pytorchnanigans"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
max = ">=24.6.0,<25"
python = "==3.12.3"
jupyter = ">=1.1.1,<2"
pytorch = ">=2.5.1,<3"
numpy = ">=1.26.4,<2"

[environments]
# implicit: default = ["default"]
cuda = ["cuda"]

[feature.cuda]
platforms = ["linux-64"]
system-requirements = {cuda = "12.4"}

[tasks]
max_scratchpad = "jupyter notebook notebooks/max_scratchpad.ipynb"
torch_scratchpad = "jupyter notebook notebooks/torch_scratchpad.ipynb"
